version: '3'

services:
  db:
    container_name: ${DB_NAME}
    build: db/
    image: db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 5s
    volumes:
      - ./.database_data:/var/lib/postgresql/data

  # db2:
  #   container_name: mysql2_${DB_NAME}
  #   image: 'mysql/mysql-server:8.0'
  #   env_file: .env
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - ${DB_PORT}:3306
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
  #     retries: 3
  #     timeout: 5s


volumes:
  .database_data:
    driver: local
